### PR TITLE
Fixes #4034: Ensure that status code is nonzero on invalid shutdown

### LINKED ISSUE #4034: drush site-install returns improper exit code
If site installation fails, Drush exists with `0`.

```
$ ./vendor/bin/drush site-install -y minimal --sites-subdir default --config-dir ../config/sync

 // You are about to DROP all tables in your 'sites/default/files/.sqlite' database. Do you want to continue?: yes.

 [notice] Starting Drupal installation. This takes a while.
TypeError: Argument 2 passed to ...
 [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.

$ echo $?
0
```

| Q               | A
| --------------- | ---
| Drush version  | 9.6.1
| Drupal version | 8.6.13
| PHP version     | 7.3.3
| OS             | Mac

Probably the same issue as in #2223

### PR DESCRIPTION
**Pull request by greg-1-anderson**
If we get to the shutdown handler in an error state, but the status code is still zero, force it to 1.

### CODE REVIEW

File: src/Runtime/ShutdownHandler.php [hunk 1]
```diff
@@ -42,6 +42,11 @@ public function shutdownHandler()
 
         if (!Drush::config()->get(Runtime::DRUSH_RUNTIME_COMPLETED_NAMESPACE)) {
             Drush::logger()->warning('Drush command terminated abnormally. Check for an exit() in your Drupal site.');
+            // Make sure that we will return an error code when we exit,
+            // even if the code that got us here did not.
+            if (!Runtime::exitCode()) {
+                Runtime::setExitCode(1);
```
Comment (weitzman) [inline src/Runtime/ShutdownHandler.php]: Lets use \Drush\Commands\DrushCommands::EXIT_FAILURE

File: src/Runtime/ShutdownHandler.php [hunk 2]
```diff
@@ -42,6 +42,11 @@ public function shutdownHandler()
 
         if (!Drush::config()->get(Runtime::DRUSH_RUNTIME_COMPLETED_NAMESPACE)) {
             Drush::logger()->warning('Drush command terminated abnormally. Check for an exit() in your Drupal site.');
+            // Make sure that we will return an error code when we exit,
+            // even if the code that got us here did not.
+            if (!Runtime::exitCode()) {
```
Comment (weitzman) [inline src/Runtime/ShutdownHandler.php]: Should we unmark this method as deprecated?

Comment (greg-1-anderson) [reply src/Runtime/ShutdownHandler.php]: I don't think so. I'd like to eventually rework exit code handling. Really, the `Runtime` class should be considered internal to Drush. We should put APIs that we want folks to use in the Drush class.
