### PR TITLE
Replace usage of Assertion\Handle::register()

### LINKED ISSUE #5734: Remove or replace usage of Assertion::handler
Currently `drush php` command triggers the following deprecation error.

> Drupal\Component\Assertion\Handle is deprecated in drupal:10.1.0 and is removed from drupal:11.0.0. Instead, use assert_options(ASSERT_EXCEPTION, TRUE). See https://drupal.org/node/3105918

Not sure if we need to remove it or replace with `assert_options(ASSERT_EXCEPTION, TRUE);`.

### PR DESCRIPTION
**Pull request by claudiu-cristea**
Fixes #5734

### CODE REVIEW

File: src/Commands/core/CliCommands.php [hunk 1]
```diff
@@ -82,9 +81,12 @@ public function cli(array $options = ['version-history' => false, 'cwd' => self:
...
 
 
-        // Register the assertion handler so exceptions are thrown instead of errors
-        // being triggered. This plays nicer with PsySH.
-        Handle::register();
+        // Register the assertion handler so exceptions are thrown instead of
+        // errors being triggered. This plays nicer with PsySH. Since we're
+        // using exceptions, turn error warnings off.
+        assert_options(ASSERT_EXCEPTION, true);
+        assert_options(ASSERT_WARNING, false);
```
Comment (andypost) [inline src/Commands/core/CliCommands.php:88]: It should have wrapper for PHP 8.3 https://php.watch/versions/8.3/assert-multiple-deprecations

**Comment by claudiu-cristea** [comment]
@andypost like this #6276?
