### PR TITLE
Reduce the default number of fields on migrate:status

### LINKED ISSUE #4690: Displayed migration ID is too short
**Describe the bug**
The output of `drush ms` has too few characters for the migration id making it very difficult to know to interpret the output of the command. The length of the displayed ID is now shorter than it was with migrate_run. In the example you can't use the ID to   distinguish between taxonomy term and vocabulary migrations. This will affect other migrations as well. Note that migrate_run also truncated the ID, which is very annoying, so ideally this could change to show the full ID.

**To Reproduce**
```
$ drush en -y migrate_drupal
$ ddev drush ms | grep taxon
```
**Expected behavior**
To see the full migration ID in the output or, at least, the same output as migrate_run.
```
$ ddev drush ms | grep taxon
 [error]  Could not retrieve source count from d6_taxonomy_term: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.term_data' doesn't exist: SELECT COUNT(*) AS "expression"
 [error]  Could not retrieve source count from d6_taxonomy_vocabulary: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.vocabulary' doesn't exist: SELECT COUNT(*) AS "expression"
  d6_taxonomy_term          Idle     N/A     0            N/A
  d6_taxonomy_vocabulary    Idle     N/A     0            N/A
  d7_taxonomy_term:sujet_   Idle     5       5 (100%)     0
  d7_taxonomy_term:tags     Idle     10      10 (100%)    0
  d7_taxonomy_term:test_v   Idle     3       3 (100%)     0
  d7_taxonomy_term:vocabf   Idle     1       1 (100%)     0
  d7_taxonomy_term:vocabl   Idle     2       2 (100%)     0
  d7_taxonomy_term:vocabl   Idle     1       1 (100%)     0
  d7_taxonomy_term:vocabt   Idle     3       3 (100%)     0
  d7_taxonomy_term:vocabu   Idle     0       0            0
  d7_taxonomy_vocabulary    Idle     8       8 (100%)     0
  taxonomy_settings         Idle     1       1 (100%)     0
```
**Actual behavior**
The migration IDs are truncated so that the ID can't be used to determine if the migration is for a d7 vocabulary or a d7 term.
```
$ ddev drush ms | grep taxon
 [error]  Could not retrieve source count from d6_taxonomy_term: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.term_data' doesn't exist: SELECT COUNT(*) AS "expression"
 [error]  Could not retrieve source count from d6_taxonomy_vocabulary: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd7_dump.vocabulary' doesn't exist: SELECT COUNT(*) AS "expression"
  d6_taxonomy_   Idle     N/A     0            N/A              N/A
  d6_taxonomy_   Idle     N/A     0            N/A              N/A
  d7_taxonomy_   Idle     5       5 (100%)     0                0
  d7_taxonomy_   Idle     10      10 (100%)    0                0
  d7_taxonomy_   Idle     3       3 (100%)     0                0
  d7_taxonomy_   Idle     1       1 (100%)     0                0
  d7_taxonomy_   Idle     2       2 (100%)     0                0
  d7_taxonomy_   Idle     1       1 (100%)     0                0
  d7_taxonomy_   Idle     3       3 (100%)     0                0
  d7_taxonomy_   Idle     0       0            0                0
  d7_taxonomy_   Idle     8       8 (100%)     0                0
```

**Workaround**
Don't use Drush 10.4. Use migrate_run with earlier version of Drush.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4
| Drupal version? | 9.2.x
| PHP version     | PHP 7.3.25
| OS?             | Linux

**Additional information**

### PR DESCRIPTION
**Pull request by claudiu-cristea**
Fixes #4690

### CODE REVIEW

File: tests/functional/MigrateRunnerTest.php [hunk 1]
```diff
@@ -75,17 +75,22 @@ public function testMigrateStatus(): void
         $this->assertEquals('test_migration_tagged', trim($output[5]['id']));
         $this->assertNull($output[6]['id']);
 
-        // Names only.
+        // Check that --name-only takes precedence over --columns.
```
Comment (weitzman) [inline tests/functional/MigrateRunnerTest.php:78]: --columns is gone now

**Comment by quietone1** [comment]
Thanks! So much better now.
