### PR TITLE
Fix #3748. Use Semver::satisfies.

### LINKED ISSUE #3748: pm:security incorrectly reports insecure package
**Describe the bug**
Last night, Drupal `8.5.8` and `8.6.2` were released as security releases. I have updated my Drupal 8.5.7 site to Drupal 8.5.8, and have `$ drush pm:security` running as part of my CI solution. This is failing my builds, because the pm:security command in incorrectly specifying that I must be on 8.6.2.

**Expected behavior**
`$ drush pm:security` command to exit successfully and not report an error.

**Actual behavior**
This fails my build:
screen shot 2018-10-18 at 11 19 23 am

**Workaround**
Not that I can see...

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4.0
| Drupal version? | 8.5.8
| PHP version     | 7.1
| OS?             | Mac & Linux

### PR DESCRIPTION
**Pull request by weitzman**
See #3748 .. This depends on a change to drupal-security-advisories.

### CODE REVIEW

File: src/Commands/pm/SecurityUpdateCommands.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ public function suggestComposerCommand($result, CommandData $commandData)
     protected function fetchAdvisoryComposerJson()
     {
         try {
-            $response_body = file_get_contents('https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x/composer.json');
+            $response_body = file_get_contents('/Users/moshe.weitzman/Downloads/d8-composer.json (2).txt'); // https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x/composer.json
```
Comment (webflo) [inline src/Commands/pm/SecurityUpdateCommands.php]: Wrong URL ;)

Comment (weitzman) [reply src/Commands/pm/SecurityUpdateCommands.php]: Woops. Fixed
