### PR TITLE
Run hook_requirements() on pm:enable

### LINKED ISSUE #4190: Module installation ignores `hook_requirements`.
**Describe the bug**
When installing a module through `drush en` the result of `hook_requirements` isn't taken into account. We've got a module that sets an requirement error if a certain environment variable is missing, when installing through the Drupal UI installation is correctly blocked, when installing through Drush the module is enabled no matter what. 

**To Reproduce**
Add a module that implements `hook_requirements` and return a requirement with the severity `REQUIREMENT_ERROR`.

**Expected behavior**
That the installation of the module would be blocked.

**Actual behavior**
The module is installed.

**Workaround**
N/A

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1 
| Drupal version? | 8.7.7
| PHP version     | 7.2.20
| OS?             | Linux

### PR DESCRIPTION
**Pull request by codebymikey**
This resolves #4190 and supersedes the #4337 PR to include functional tests as well as read all requirement errors.

### CODE REVIEW

File: src/Drupal/Commands/pm/PmCommands.php [hunk 1]
```diff
@@ -87,6 +99,8 @@ public function enable(array $modules)
             }
         }
 
+        $this->validateInstallModules($todo);
```
Comment (weitzman) [inline src/Drupal/Commands/pm/PmCommands.php:102]: - You can remove this line and instead add `@hook validate pm:enable` at top of validateInstallModules method. 
- I think this method should be called `validateEnableModules`

File: src/Drupal/Commands/pm/PmCommands.php [hunk 2]
```diff
@@ -279,6 +293,39 @@ public function addInstallDependencies($modules)
...
+                    if (isset($requirement['severity']) && $requirement['severity'] == REQUIREMENT_ERROR) {
+                        $message = $requirement['description'];
+                        if (isset($requirement['value']) && $requirement['value']) {
+                            $message = dt('@requirements_message (Currently using @item version @version)', ['@requirements_message' => $requirement['description'], '@item' => $requirement['title'], '@version' => $requirement['value']]);
+                        }
+                        $reasons[$id] = $message;
+                    }
+                }
+
+                throw new \Exception(sprintf("Unable to install module '%s' due to unmet requirement(s):%s", $module, "\n  - " . implode("\n  - ", $reasons)));
```
Comment (weitzman) [inline src/Drupal/Commands/pm/PmCommands.php:324]: Thanks. Given our long history of not validating this, lets give the user the option to proceed despite the validation error. See https://github.com/drush-ops/drush/blob/10.x/src/Commands/core/UpdateDBCommands.php#L54-L59 for an example from updatedb.

**Review by weitzman — CHANGES_REQUESTED** [review]

File: src/Drupal/Commands/pm/PmCommands.php (hunk 2 above)
Comment (codebymikey) [reply src/Drupal/Commands/pm/PmCommands.php]: All done, it'll default to `false` in order to fail by default.

Comment (weitzman) [reply src/Drupal/Commands/pm/PmCommands.php]: Lets default to continue like updatedb does (i.e. no exception). Otherwise we will have to wait for a major version for this.

Comment (codebymikey) [reply src/Drupal/Commands/pm/PmCommands.php]: I've updated the logic and test to reflect that.

And yes, that makes sense since we want to maintain backwards compatibility and avoid breaking any existing integrations/tests which rely on it (but one could also argue that if the module being installed doesn't meet the platform requirements in the first place, there's something wrong with their integration, and the failure _should_ be the appropriate default behaviour, and should lead to them fixing it on their end, and opt out with `--no`).
